name: build
on:
  push:
    branches:
    - master
    - v*
    tags:
    - v*
  pull_request:
jobs:
  build:
    name: Build binaries
    runs-on: longhorn-infra-oracle-arm64-spdk-runners
    steps:
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Install curl make git
      run: |
        sudo apt update
        sudo apt install -y curl make git

    # Build binaries
    - name: Run ci
      run: make ci

    - uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
      with:
        files: ./coverage.out
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}
